language: go

matrix:
  include:
   - go: 1.6.2

env:
  global:
   - PATH=$GOPATH/bin:$PATH

install:
  - go install ./vendor/github.com/onsi/ginkgo/ginkgo

script: ginkgo -p -r --randomizeAllSpecs --randomizeSuites --race --trace
